### ISSUE TITLE
finch vm init fails ("Terminal is not available, proceeding without opening an editor")

### ISSUE THREAD

**Issue by github-1pacific** [runfinch/finch#59]
I tried to initialize Finch but finch vm init fails in my environment.

```
% uname -v
Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64
% sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H15
```

Error Message:

```
% finch vm init
INFO[0000] binaries directory doesn't exist
INFO[0000] Requesting root access to finish network dependency configuration
Password:
INFO[0004] Initializing and starting Finch virtual machine...
ERRO[0010] Finch virtual machine failed to start, debug logs: time="2022-11-27T14:29:40+09:00" level=info msg="Terminal is not available, proceeding without opening an editor"
time="2022-11-27T14:29:40+09:00" level=info msg="Starting socket_vmnet daemon for \"finch-shared\" network"
time="2022-11-27T14:29:40+09:00" level=info msg="Attempting to download the image from \"/Applications/Finch/os/Fedora-Cloud-Base-37-1.7.x86_64.qcow2\"" digest="sha256:b5b9bec91eee65489a5745f6ee620573b23337cbb1eb4501ce200b157a01f3a0"
time="2022-11-27T14:29:42+09:00" level=info msg="Downloaded the image from \"/Applications/Finch/os/Fedora-Cloud-Base-37-1.7.x86_64.qcow2\""
time="2022-11-27T14:29:43+09:00" level=info msg="Attempting to download the nerdctl archive from \"https://github.com/containerd/nerdctl/releases/download/v1.0.0/nerdctl-full-1.0.0-linux-amd64.tar.gz\"" digest="sha256:b7f76a3bf1b8161eb94ebe885945feb2887dfc0d274f9da908a17bc0ef853eb9"
time="2022-11-27T14:29:43+09:00" level=info msg="Using cache \"/Users/nakamura/Library/Caches/lima/download/by-url-sha256/86e8280c3d639367efe7a50660ecfc4eade10b1696a9deeba27fdbf086d11098/data\""
time="2022-11-27T14:29:46+09:00" level=error msg="[hostagent] failed to run [/Applications/Finch/lima/bin/qemu-system-x86_64 -M none -accel help]: stdout=\"\", stderr=\"dyld: Symbol not found: _vmnet_enable_isolation_key\\n  Referenced from: /Applications/Finch/lima/bin/qemu-system-x86_64 (which was built for Mac OS X 11.0)\\n  Expected in: /System/Library/Frameworks/vmnet.framework/Versions/A/vmnet\\n in /Applications/Finch/lima/bin/qemu-system-x86_64\\n\"" fields.level=fatal
time="2022-11-27T14:29:46+09:00" level=fatal msg="host agent process has exited: exit status 1"
FATA[0010] exit status 1
%
```

Any help would be greatly appreciated.

**Comment by AkihiroSuda** [comment]
Duplicate of 
- #53

**Comment by KevinLiAWS** [comment]
Currently the exectuables are built on Mac OS 11, so it is not compatable with lower version. We are working on a fix to support Mac OS 10.15

**Comment by KevinLiAWS** [comment]
As it is the same issue with https://github.com/runfinch/finch/issues/53, resolve and tracking with #53

**Comment by himan085** [comment]
I'm facing the same issue on macOS Ventura 13.4.

**Comment by KevinLiAWS** [comment]
Hi @himan085, could you provide the supported bundle by running:
`finch support-bundle generate`
Thanks

**Comment by himan085** [comment]
I was facing this error, but to my surprise when I started the VM by running the `start` command, it worked successfully.
