### ISSUE TITLE
```finch vm init``` ```finch vm start``` Finch virtual machine failed to start. Symbol not found

### ISSUE THREAD

**Issue by Azunyan1111** [runfinch/finch#53]
**Describe the bug**
I am unable to start a VM on my Macbook pro (10.15.4).

When I run ```finch vm init```, I get the logs listed at the bottom, and  ```finch vm start``` gives the same message.

These prevent me from running finch.

**Steps to reproduce**
1. install Finch from using Finch-v0.1.0-x86_64.pkg
2. run the ```finch vm init ``` command and log at the bottom
3. run ``finch vm start`` command and log at bottom

**Screenshots or logs**
```
$ finch vm init 
INFO[0000] Using default values due to missing config file at "/Users/admin/.finch/finch.yaml" 
INFO[0000] "/Users/admin/.finch" directory doesn't exist, attempting to create it 
INFO[0000] binaries directory doesn't exist             
INFO[0000] Requesting root access to finish network dependency configuration 
Password:
INFO[0003] sudoers file not found: %!w(*fs.PathError=&{open /etc/sudoers.d/finch-lima 2}) 
INFO[0003] Initializing and starting Finch virtual machine... 
ERRO[0032] Finch virtual machine failed to start, debug logs: time="2022-11-25T06:53:20+09:00" level=info msg="Terminal is not available, proceeding without opening an editor"
time="2022-11-25T06:53:20+09:00" level=info msg="Starting socket_vmnet daemon for \"finch-shared\" network"
time="2022-11-25T06:53:20+09:00" level=info msg="Attempting to download the image from \"/Applications/Finch/os/Fedora-Cloud-Base-37-1.7.x86_64.qcow2\"" digest="sha256:b5b9bec91eee65489a5745f6ee620573b23337cbb1eb4501ce200b157a01f3a0"
time="2022-11-25T06:53:22+09:00" level=info msg="Downloaded the image from \"/Applications/Finch/os/Fedora-Cloud-Base-37-1.7.x86_64.qcow2\""
time="2022-11-25T06:53:25+09:00" level=info msg="Attempting to download the nerdctl archive from \"https://github.com/containerd/nerdctl/releases/download/v1.0.0/nerdctl-full-1.0.0-linux-amd64.tar.gz\"" digest="sha256:b7f76a3bf1b8161eb94ebe885945feb2887dfc0d274f9da908a17bc0ef853eb9"

76.00 MiB / 221.66 MiB (34.29%) ? p/s
140.00 MiB / 221.66 MiB (63.16%) 12.79 MiB/s
196.00 MiB / 221.66 MiB (88.42%) 12.69 MiB/s
221.66 MiB / 221.66 MiB (100.00%) 15.71 MiB/stime="2022-11-25T06:53:45+09:00" level=info msg="Downloaded the nerdctl archive from \"https://github.com/containerd/nerdctl/releases/download/v1.0.0/nerdctl-full-1.0.0-linux-amd64.tar.gz\""
time="2022-11-25T06:53:50+09:00" level=error msg="[hostagent] failed to run [/Applications/Finch/lima/bin/qemu-system-x86_64 -M none -accel help]: stdout=\"\", stderr=\"dyld: Symbol not found: _vmnet_enable_isolation_key\\n  Referenced from: /Applications/Finch/lima/bin/qemu-system-x86_64 (which was built for Mac OS X 11.0)\\n  Expected in: /System/Library/Frameworks/vmnet.framework/Versions/A/vmnet\\n in /Applications/Finch/lima/bin/qemu-system-x86_64\\n\"" fields.level=fatal
time="2022-11-25T06:53:50+09:00" level=fatal msg="host agent process has exited: exit status 1" 
FATA[0032] exit status 1         
```

```
$ finch vm start
INFO[0000] Starting existing Finch virtual machine...   
ERRO[0001] Finch virtual machine failed to start, debug logs: time="2022-11-25T07:00:16+09:00" level=info msg="Using the existing instance \"finch\""
time="2022-11-25T07:00:16+09:00" level=info msg="Attempting to download the nerdctl archive from \"https://github.com/containerd/nerdctl/releases/download/v1.0.0/nerdctl-full-1.0.0-linux-amd64.tar.gz\"" digest="sha256:b7f76a3bf1b8161eb94ebe885945feb2887dfc0d274f9da908a17bc0ef853eb9"
time="2022-11-25T07:00:16+09:00" level=info msg="Using cache \"/Users/admin/Library/Caches/lima/download/by-url-sha256/86e8280c3d639367efe7a50660ecfc4eade10b1696a9deeba27fdbf086d11098/data\""
time="2022-11-25T07:00:18+09:00" level=error msg="[hostagent] failed to run [/Applications/Finch/lima/bin/qemu-system-x86_64 -M none -accel help]: stdout=\"\", stderr=\"dyld: Symbol not found: _vmnet_enable_isolation_key\\n  Referenced from: /Applications/Finch/lima/bin/qemu-system-x86_64 (which was built for Mac OS X 11.0)\\n  Expected in: /System/Library/Frameworks/vmnet.framework/Versions/A/vmnet\\n in /Applications/Finch/lima/bin/qemu-system-x86_64\\n\"" fields.level=fatal
time="2022-11-25T07:00:18+09:00" level=fatal msg="host agent process has exited: exit status 1" 
FATA[0001] exit status 1  
```

**Comment by KevinLiAWS** [comment]
Seems like some dependencies were built on higher os version, which may result in the failure:
`/Applications/Finch/lima/bin/qemu-system-x86_64 (which was built for Mac OS X 11.0)`
We will try some lower version os and reproduce the issue.

**Comment by Azunyan1111** [comment]
@KevinLiAWS  Thanks for the reply.
I replaced ``qemu-system-x86_64`` with a binary file that works with 10.15 as you suggested and it worked!

Not a nice do it,but I'll leave a note on what I did to fix it

```
$ brew install qemu
omit...

$ brew list qemu # find qemu path
/usr/local/Cellar/qemu/7.1.0/bin/elf2dmp
....

$ ls /usr/local/Cellar/qemu/7.1.0/bin/qemu-system-x86_64 # qemu-system-x86_64 is here
/usr/local/Cellar/qemu/7.1.0/bin/qemu-system-x86_64

$ cd /Applications/Finch/lima/bin
$ mv qemu-system-x86_64 ~/ # backup
$ cp /usr/local/Cellar/qemu/7.1.0/bin/qemu-system-x86_64 . # replace
```

**Comment by KevinLiAWS** [comment]
@Azunyan1111 Thank you so much for testing it out. It verified that the binaries compatable with the supported os version to fix this issue. I will keep you updated for the fix.

**Comment by KevinLiAWS** [comment]
This issue got fixed in the new release v0.1.1. Now 10.15(intel chip) is able to run finch.
